version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"
    allow:
      - dependency-type: "indirect"
  - package-ecosystem: "gomod"
    directory: "/outbox/"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"
    allow:
      - dependency-type: "indirect"
